openapi: 3.0.1
info:
  contact:
    email: thomas.yu@sagebionetworks.org
  description: |
    This is the submission API to obtain the metadata of the submission
    and send the submission to execute in the right workflow environment
  license:
    name: Apache-2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  termsOfService: challenge.org
  title: Submission API
  version: 1.0.0
servers:
  - url: /
tags:
  - description: Ceate and link synapse queues with workflow engines
    name: Queue
  - description: Compute environment
    name: Compute
  - description: Allow synapse submissions to interact with supported workflow engines
    externalDocs:
      description: Mimics GA4GH
      url: 'https://github.com/ga4gh/workflow-execution-service-schemas'
    name: Execution
  - description: Submission and its metadata
    externalDocs:
      description: More about submission references
      url: >-
        https://rest-docs.synapse.org/rest/#org.sagebionetworks.repo.web.controller.EvaluationController
    name: Submission
paths:
  /queues:
    $ref: paths/queues.yaml
  /queues/{queueId}:
    $ref: paths/queues@{queueId}.yaml
  /queues/{queueId}/submissions:
    $ref: paths/submissions.yaml
  /queues/{queueId}/submissions/{submissionId}:
    $ref: paths/submissions@{submissionId}.yaml
  /queues/{queueId}/submissions/{submissionId}/status:
    $ref: paths/status.yaml
  /queues/{queueId}/submissions/{submissionId}/runs:
    $ref: paths/runs.yaml
  /queues/{queueId}/submissions/{submissionId}/runs/{runId}:
    $ref: paths/runs@{runId}.yaml
  /queues/{queueId}/submissions/{submissionId}/runs/{runId}/log:
    $ref: paths/log.yaml
  /computeEnvs:
    $ref: paths/computeEnvs.yaml
  /computeEnvs/{computeEnvId}:
    $ref: paths/computeEnvs@{computeEnvId}.yaml