# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class SubmissionData(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, payload=None, file=None, docker=None):  # noqa: E501
        """SubmissionData - a model defined in OpenAPI

        :param payload: The payload of this SubmissionData.  # noqa: E501
        :type payload: file
        :param file: The file of this SubmissionData.  # noqa: E501
        :type file: file
        :param docker: The docker of this SubmissionData.  # noqa: E501
        :type docker: str
        """
        self.openapi_types = {
            'payload': file,
            'file': file,
            'docker': str
        }

        self.attribute_map = {
            'payload': 'payload',
            'file': 'file',
            'docker': 'docker'
        }

        self._payload = payload
        self._file = file
        self._docker = docker

    @classmethod
    def from_dict(cls, dikt) -> 'SubmissionData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Submission_data of this SubmissionData.  # noqa: E501
        :rtype: SubmissionData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def payload(self):
        """Gets the payload of this SubmissionData.

        JSON inputs to workflow  # noqa: E501

        :return: The payload of this SubmissionData.
        :rtype: file
        """
        return self._payload

    @payload.setter
    def payload(self, payload):
        """Sets the payload of this SubmissionData.

        JSON inputs to workflow  # noqa: E501

        :param payload: The payload of this SubmissionData.
        :type payload: file
        """

        self._payload = payload

    @property
    def file(self):
        """Gets the file of this SubmissionData.

        File submission  # noqa: E501

        :return: The file of this SubmissionData.
        :rtype: file
        """
        return self._file

    @file.setter
    def file(self, file):
        """Sets the file of this SubmissionData.

        File submission  # noqa: E501

        :param file: The file of this SubmissionData.
        :type file: file
        """

        self._file = file

    @property
    def docker(self):
        """Gets the docker of this SubmissionData.

        Docker + shadigest submmission  # noqa: E501

        :return: The docker of this SubmissionData.
        :rtype: str
        """
        return self._docker

    @docker.setter
    def docker(self, docker):
        """Sets the docker of this SubmissionData.

        Docker + shadigest submmission  # noqa: E501

        :param docker: The docker of this SubmissionData.
        :type docker: str
        """

        self._docker = docker
